{{- if .Values.custom.pgpool.customUsersSecret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.custom.pgpool.customUsersSecret.name }}
  labels:  {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
spec:
  backendType: secretsManager
  data: {{- toYaml .Values.custom.pgpool.customUsersSecret.secrets | nindent 4 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
{{- end }}
---
{{- if .Values.custom.pgpool.existingSecret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.custom.pgpool.existingSecret.name }}
  labels:  {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
spec:
  backendType: secretsManager
  data: {{- toYaml .Values.custom.pgpool.existingSecret.secrets | nindent 4 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
{{- end }}
